Feature/investment tests
RacyMind/kalkulator-dla-przedsiebiorcy-vue pull request #84
Opened 2023-01-29 17:37 UTC by dithh

2023-01-30 14:45 UTC, RacyMind requested changes
Please also solve conflicts. I fixed one test and added edge cases for invoice tests

2023-01-30 14:45 UTC, RacyMind commented on test/jest/__tests__/investment/investment.spec.ts
> +describe('investment',()=>{
Generally, it should also check edge cases when one of inputs is equal to 0. I know UI doesn't allow to set 0 but calculations should be correct. The UI might be changed in the future

2023-01-31 17:17 UTC, dithh commented
@RacyMind  requested changes done

2023-02-03 17:43 UTC, RacyMind requested changes

2023-02-03 17:43 UTC, RacyMind commented on test/jest/__tests__/investment/investment.spec.ts
> +    const {capital,grossAmount,netAmount,taxAmount} = investment.getResult({...defaultInput,rate:0})
`amount` should be here :)

2023-02-04 14:44 UTC, dithh commented on test/jest/__tests__/investment/investment.spec.ts
> +    const {capital,grossAmount,netAmount,taxAmount} = investment.getResult({...defaultInput,rate:0})
done

2023-02-04 14:54 UTC, RacyMind approved these changes

2023-02-04 14:57 UTC, merged