#79 - feat: dockerize
RacyMind/kalkulator-dla-przedsiebiorcy-vue pull request #86
Opened 2023-01-31 19:15 UTC by km4

2023-02-04 14:28 UTC, dithh commented
super, ze jest docker.
ale czy frontowych appkach czas potrzebny na skonfigurwoanie dockera przynosi faktycznie wymierne korzysci?
mamy nvm, wiec zmiana wersji node to jedna linijka w terminalu.
jakie jeszcze sa zalety?
pytam z czystej ciekawosci, to nie hejt :D

2023-02-05 09:44 UTC, km4 commented
Nie wiem jaki zamysł miał twórca issue. W tak małym projekcie jest mały gain jeśli chodzi o dokeryzacje (w developmencie). Jak dobre zauwazyles nvm załatwia wiekszosc spraw, jednak nie każdy wie że coś takiego istnieje.

2023-02-06 13:46 UTC, lsochaSopamo commented
> Nie wiem jaki zamysł miał twórca issue. W tak małym projekcie jest mały gain jeśli chodzi o dokeryzacje (w developmencie). Jak dobre zauwazyles nvm załatwia wiekszosc spraw, jednak nie każdy wie że coś takiego istnieje.

Na grupie programistycznej, gdzie wrzuciłem info o kalkulatorze, kilka osób zasugerowało dodanie Dockera, by nie było problemu z różnymi wersjami node. Dla mnie także nvm jest wystarczający. Zdecydowałem się dodać issue z Dockerem, ponieważ dodanie Dockera nie jest jakoś skomplikowane dla kalkulatora, a dla części programistów może być przydatny. Przy projekcie open source trzeba zapewnić wsparcie programistom z różnym podejściem.

2023-02-06 13:49 UTC, lsochaSopamo requested changes

2023-02-06 13:49 UTC, lsochaSopamo commented on Dockerfile
> +COPY . .
Pliki są kopiowane na etapie tworzenia obrazu, więc nie widać zmian w kodzie. Sugeruję użycie `volumes`

2023-02-07 18:27 UTC, km4 commented on Dockerfile
> +COPY . .
spoko, podepne volumen :)

2023-02-14 13:15 UTC, RacyMind requested changes
Podczas próby uruchomienia mam następujące błędy 
![image](https://user-images.githubusercontent.com/12596694/218749663-249d2857-d3e3-475a-aa11-f4b72d2fe9d9.png)

2023-02-15 19:33 UTC, km4 commented
> Podczas próby uruchomienia mam następujące błędy ![image](https://user-images.githubusercontent.com/12596694/218749663-249d2857-d3e3-475a-aa11-f4b72d2fe9d9.png)

2023-02-15 19:33 UTC, closed without merging

2023-02-16 19:23 UTC, km4 commented
> Podczas próby uruchomienia mam następujące błędy ![image](https://user-images.githubusercontent.com/12596694/218749663-249d2857-d3e3-475a-aa11-f4b72d2fe9d9.png)

w takim wypadku pewnie musisz zmienic uprawnienia albo trzeba pierw utworzyc wolumen. co wolisz ? jakis tip ?